import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { sha256Hex } from "@livebic/core";
import { buildApp } from "../src/app";
import { loadConfig } from "../src/config";
import { createContext } from "../src/context";
import { loadBundle } from "../src/migrate/bundle";
import { mapDeepSound, portablePasswordHash, settlementCsv, type DeepSoundRows, type DsUser } from "../src/migrate/deepsound";
import { sandboxPartners } from "../src/partners/sandbox";
import { MemoryStore } from "../src/store";

/** Generated by PHP: password_hash('tobipass', PASSWORD_DEFAULT) */
const PHP_HASH = "$2y$10$K63jmgQns2cbWgVDTj6i6OZEFVCDOdAmi.xTMB7lBUzuFxuKHjumG";

const user = (p: Partial<DsUser> & { id: number; username: string; email: string }): DsUser => ({
  password: PHP_HASH, name: p.username, about: "", facebook: null, twitter: null, instagram: null, website: null,
  active: 1, admin: 0, verified: 0, artist: 0, registered: "2022/1", time: 1_650_000_000, balance: 0, wallet: 0, ...p,
});

function rows(): DeepSoundRows {
  return {
    config: { currency: "USD" },
    users: [
      user({ id: 2, username: "Tobi.Lagos", email: "Tobi@Site.ng", artist: 1, verified: 1, balance: "120.5" }),
      user({ id: 3, username: "ada", email: "ada@site.ng" }),
      user({ id: 4, username: "fan1", email: "fan1@site.ng", wallet: "10" }),
      user({ id: 5, username: "dup", email: "FAN1@site.ng" }),
      user({ id: 7, username: "old", email: "old@site.ng", password: "11f6ad8ec52a2984abaafd7c3b516503785c2072" }),
    ],
    songs: [
      { id: 10, user_id: 2, audio_id: "aaa111", title: "Danfo Driver", description: "", lyrics: "", thumbnail: "upload/photos/c.jpg", availability: 0, price: 0, audio_location: "upload/audio/a.mp3", time: 1_700_000_000 },
      { id: 11, user_id: 2, audio_id: "bbb222", title: "Third Mainland", description: "", lyrics: "", thumbnail: "upload/photos/thumbnail.jpg", availability: 0, price: "2.99", audio_location: "upload/audio/b.mp3", time: 1_700_100_000 },
      { id: 12, user_id: 3, audio_id: "ccc333", title: "Private Demo", description: "", lyrics: "", thumbnail: "", availability: 1, price: 0, audio_location: "upload/audio/c.mp3", time: 1_700_200_000 },
    ],
    followers: [
      { id: 1, follower_id: 4, following_id: 2, time: 1_700_000_500 },
      { id: 2, follower_id: 2, following_id: 4, time: 1_700_000_600 },
    ],
    likes: [{ id: 1, track_id: 10, user_id: 4, time: 1_700_000_800 }],
    views: [{ id: 1, track_id: 10, user_id: 0, fingerprint: "fp", time: 1_700_001_000 }],
    purchases: [
      { id: 1, user_id: 4, track_id: 11, event_id: 0, price: "2.99", final_price: "1.495", time: 1_700_002_000 },
      { id: 2, user_id: 4, track_id: 0, event_id: 1, price: "10", final_price: "5", time: 1_700_003_000 },
    ],
    withdrawals: [
      { id: 1, user_id: 2, amount: "50", currency: "USD", status: 0, requested: null, type: "bank" },
      { id: 2, user_id: 2, amount: "20", currency: "USD", status: 1, requested: null, type: "bank" },
    ],
    notMigrated: { playlists: 3 },
  };
}

describe("DeepSound mapping", () => {
  it("needs a naira rate when the old site priced in another currency", () => {
    expect(() => mapDeepSound(rows())).toThrow(/ngn-per-unit/);
  });

  it("maps users, artists, releases, history and money to settle", () => {
    const { bundle, report } = mapDeepSound(rows(), { ngnPerUnit: 1550 });
    expect(bundle.users.map((u) => u.email)).toEqual(["tobi@site.ng", "ada@site.ng", "fan1@site.ng", "old@site.ng"]);
    expect(report.skipped["user with a duplicate email"]).toBe(1);
    expect(report.usersNeedingPasswordReset).toBe(1);

    expect(bundle.artists.map((a) => [a.handle, a.verification])).toEqual([["tobi_lagos", "verified"], ["ada", "unverified"]]);
    expect(report.promotedToArtist).toBe(1);

    const [danfo, third, demo] = bundle.releases;
    expect(danfo).toMatchObject({ access: "public", status: "published", cover: { legacyPath: "upload/photos/c.jpg" } });
    expect(third).toMatchObject({ access: "paid", priceKobo: 463_450, cover: null });
    expect(demo!.status).toBe("draft");

    expect(bundle.orders).toEqual([expect.objectContaining({ id: "ord_ds1", amountKobo: 463_450, legacy: { source: "deepsound", currency: "USD", amount: 2.99 } })]);
    expect(bundle.events.map((e) => e.type).sort()).toEqual(["follow", "like", "play", "unlock"]);
    expect(bundle.events.find((e) => e.type === "play")!.actorId).toBe("anon_ds_fp");

    expect(report.settlement).toEqual([
      expect.objectContaining({ legacyUserId: 2, earningsBalance: 120.5, pendingWithdrawal: 50 }),
      expect.objectContaining({ legacyUserId: 4, walletCredit: 10 }),
    ]);
    expect(settlementCsv(report)).toContain("2,Tobi.Lagos,Tobi@Site.ng,120.5,0,50");
  });

  it("accepts PHP password hashes", () => {
    expect(portablePasswordHash(PHP_HASH)).toMatch(/^\$2b\$/);
    expect(portablePasswordHash("5f4dcc3b5aa765d61d8327deb882cf99")).toBeNull();
  });
});

describe("loading an import", () => {
  async function setup() {
    const { bundle } = mapDeepSound(rows(), { ngnPerUnit: 1550 });
    const mediaDir = await mkdtemp(join(tmpdir(), "ds-media-"));
    for (const m of bundle.releases.flatMap((r) => [r.audio, r.cover])) {
      if (!m) continue;
      const body = Buffer.from(`file:${m.legacyPath}`);
      m.sha256 = sha256Hex(body);
      m.bytes = body.length;
      await writeFile(join(mediaDir, m.sha256), body);
    }
    const config = loadConfig({ LIVEBIC_SANDBOX: "false" });
    const partners = sandboxPartners({ publicApiUrl: config.publicApiUrl, webhookSecret: config.processorWebhookSecret });
    const ctx = createContext({ config, store: new MemoryStore(), partners });
    const loaded = await loadBundle(ctx, bundle, mediaDir);
    return { ctx, partners, loaded, bundle, mediaDir, app: await buildApp(ctx) };
  }

  it("keeps passwords, history and old links, without crediting old money", async () => {
    const { ctx, app, loaded, partners } = await setup();
    expect(loaded).toMatchObject({ users: 4, artists: 2, releases: 3, orders: 1, follows: 1 });
    expect(partners.registry.filter((r) => r.kind === "content")).toHaveLength(3);

    const login = (body: object) => app.inject({ method: "POST", url: "/v1/auth/login", payload: body });
    expect((await login({ login: "Tobi.Lagos", password: "tobipass" })).statusCode).toBe(200);
    expect((await login({ email: "tobi@site.ng", password: "nope" })).statusCode).toBe(401);
    // Production mode: no passwordless sign-in, even for accounts that exist.
    expect((await login({ email: "old@site.ng" })).statusCode).toBe(501);
    for (let i = 0; i < 5; i++) await login({ login: "fan1", password: "wrong" });
    expect((await login({ login: "fan1", password: "tobipass" })).statusCode).toBe(429);

    const token = (await login({ login: "tobi.lagos", password: "tobipass" })).json().token;
    const csv = await app.inject({ method: "GET", url: "/v1/artists/me/supporters.csv", headers: { authorization: `Bearer ${token}` } });
    expect(csv.body).toContain("fan1,fan1@site.ng,supporter,4634.50,1");
    expect(ctx.store.ledger).toEqual([]);

    expect((await app.inject({ method: "GET", url: "/v1/legacy/tracks/aaa111" })).json()).toEqual({ releaseId: "rel_ds10", handle: "tobi_lagos" });
    expect((await app.inject({ method: "GET", url: "/v1/legacy/tracks/ccc333" })).statusCode).toBe(404);
    expect((await app.inject({ method: "GET", url: "/v1/legacy/users/Tobi.Lagos" })).json()).toEqual({ handle: "tobi_lagos" });

    const release = (await app.inject({ method: "GET", url: "/v1/releases/rel_ds10" })).json();
    const cover = await app.inject({ method: "GET", url: new URL(release.coverUrl).pathname });
    expect(cover.statusCode).toBe(200);
    expect(cover.headers["content-type"]).toBe("image/jpeg");
  });

  it("is safe to load twice", async () => {
    const { ctx, bundle, mediaDir } = await setup();
    const again = await loadBundle(ctx, bundle, mediaDir);
    expect(Object.values(again).every((n) => n === 0)).toBe(true);
  });
});
